### ISSUE TITLE
Issue with redis

### ISSUE THREAD

**Issue by davidthurston1** [MagePsycho/magento2-db-code-backup-bash-script#6]
When redis is enabled for sessions a variable called 'host' exists within this part of the config.
When the script runs the following command
grep host "app/etc/env.php" | cut -d "'" -f 4

It returns 2 lines. In my case it returns the following
localhost (from the db config)
127.0.0.1 (from the session config)

This breaks the mysqldump command.  
For now I have manually entered localhost into the script instead of letting it look it up in env.php, but the script needs a means of differentiating between multiple 'host' variables in env.php

Below is my session config for reference. 
    'session' => [
        'save' => 'redis',
        'redis' => [
            'host' => '127.0.0.1',
            'port' => '6379',
            'password' => '',
            'timeout' => '2.5',
            'persistent_identifier' => '',
            'database' => '2',
            'compression_threshold' => '2048',
            'compression_library' => 'gzip',
            'log_level' => '1',
            'max_concurrency' => '6',
            'break_after_frontend' => '5',
            'break_after_adminhtml' => '30',
            'first_lifetime' => '600',
            'bot_first_lifetime' => '60',
            'bot_lifetime' => '7200',
            'disable_locking' => '0',
            'min_lifetime' => '60',
            'max_lifetime' => '2592000'
        ]
    ],

**Comment by MagePsycho** [comment]
Thanks for reporting.
This should FIX
```
grep -m 1 host "app/etc/env.php" | cut -d "'" -f 4
```

*This issue has been fixed*
